print("Tôi đang học Python!")
print("Tôi tên là Trường")
print("Tôi 23 tuổi")
print("Tôi đang sống ở hà Nội")
print("---")
print("*****")
print("*****")
print("*****")
print("---")
print("Hôm nay tôi bắt đầu học lập trình.")
print("Tôi sẽ cố gắng mỗi ngày.")